server:
  port: 8082
  servlet:
    contextPath: /BookStore
spring:
  datasource:
    password: nico00747
    url: jdbc:mysql://localhost:3306/bookstoredb?user= Alucard
    driverClassName: com.mysql.cj.jdbc.Driver


